version: 2
jobs:
  pre:
    # Install a few packages which will be needed for building the cross compiler.
    - sudo apt update
    - sudo apt install bison
    - sudo apt install flex
    - sudo apt install libgmp3-dev
    - sudo apt install libmpc-dev
    - sudo apt install libmpfr-dev
    - sudo apt install texinfo
    - sudo apt install libisl-dev
    - sudo apt install libcloog-isl-dev

    # Build the cross compiler for your chosen target (replace i786-pc-elf if necessary).
    - chmod +x setup.sh
    - bash setup.sh

  cache_directories:
    # Add the folder with our cross compiler to the cache. This way it will be kept between builds.
    - ~/cross

compile:
  override:
    # Place here whatever commands are necessary to build your project.
    - mkdir build
    - cd build
    - cmake ..

    # Copy any files you want to keep to the folder $CIRCLE_ARTIFACTS.
    - cp bin/apotheosis.bin $CIRCLE_ARTIFACTS/

test:
  override:
    # You must place something here, even it it's just testing whether the output exists.
    - test -f $CIRCLE_ARTIFACTS/apotheosis.bin
